server:
  port: 8098
#  servlet:
#    context-path: /user_server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8099/eureka/eureka/
spring:
  application:
    name: user-server